# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: tangunhackathon  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project
  JAVA_VERSION: '1.8' # set this to the java version to use
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # set GH repo secret with the publish profile of the web app

jobs:
  build:

    runs-on: ubuntu-latest
    #environment: dev

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    
    #- name: Set up JDK 11
    #  uses: actions/setup-java@v2
    #  with:
    #    java-version: '11'
    #    distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
    - name: List out directory contents
      run: |
          echo "Listing the contents of the GitHub workspace directory"
          ls ${{ github.workspace }}
          echo "Recursively listing all contents of the current directory"
          ls -R
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.AZURE_WEBAPP_NAME }}
        path: ${{ github.workspace }}/target/*.jar
        
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/target/*.jar

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
